### ISSUE TITLE
Project State

### ISSUE THREAD

**Issue by juannorris** [nimbit-software/gojson-rules-engine#3]
Hi @nimbit-software @cpars-innovation 👋

First of all, thanks for porting this great library to Go, kudos!

I'm currently evaluating different rule engine options for my project.

I noticed there hasn't been any activity in over 2 months and even spotted a bug in one of the core pieces (for which I'm happy to submit a PR), so I was wondering about the plans for this project, are you going to continue improving/maintaining it or is it abandoned?

Thanks in advance, regards!

**Comment by nimbit-software** [comment]
Hi there, I want to keep this going. I really like the original project but i think it can be faster. I just basically ported it as is without to much thought for the performance but its something i want to get rolling and hopefully get other developers to get in on it too. 

Its not dead just getting started :) 

Any prs are very welcome

**Comment by nimbit-software** [comment]
Got some great feedback here https://www.reddit.com/r/golang/s/If9DGKtIo7

Gonna structure the tasks and work through them. Open for any ideas though.

**Comment by jnorris-rbi** [comment]
Hi @nimbit-software 👋

Thanks for the quick reply!

Glad to hear this is active. I'd be happy to participate whenever I can, although small disclaimer, I'm very new to Go.

I'll submit a PR later tonight for the bug I mentioned and open an issue for 1 more that I ran into after my initial comment here.

**Comment by nimbit-software** [comment]
Great to hear ill take a look. Im gonna try and take some time to plan the next steps and tasks. Maybe we can motivate some more people. 

The basis of it is quite simple, but i think there is a lot of potential for improving the performance.

Look forward to your help

**Comment by nimbit-software** [comment]
@jnorris-rbi I basically rewrote 60% of the project. I added stonger types and increased the performace many times over. Let me know what you think. Im gonna be adding operator decorators too so ill let you know when that goes through

**Comment by jnorris-rbi** [comment]
Hey @nimbit-software 👋 Apologies, I have a tight deadline this week, so I haven't had a chance to look at your changes yet, but I'm interested in doing so. I'll try to carve some time by the end of the week.

**Comment by juannorris** [comment]
Hi @nimbit-software 👋

Apologies, I have a tight deadline this week, so I haven't had a chance to look at your changes yet, but I'm interested in doing so. I'll try to carve some time by the end of the week.

Also, I just realized I made the mistake of using my github user from my previous job in a comment, this is the right one (my personal account): @juannorris
